language: node_js
sudo: false

matrix:
  include:
    - node_js: '8'
      script: npm run test

    - node_js: '9'
      script:
        - npm run test
      deploy:
        provider: npm
        email: ${AUTHOR_EMAIL_ADDR}
        api_key: ${AUTHOR_NPM_API_KEY}
        skip_cleanup: true
        on:
          branch: master
